apiVersion: v1
kind: ConfigMap
metadata:
  name: rotardv-painel-configmap
  namespace: rotardv-prod
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://rotardv-api.luisfelipe.dpdns.org"
  API_URL_SERVER_SIDED: "http://rotardv-api-service.rotardv-prod.svc.cluster.local"
  NEXTAUTH_URL: "https://rotardv.luisfelipe.dpdns.org"
  NEXT_PUBLIC_APP_LOGO_URL: "https://rota-rdv.web.fslab.dev/7c4bb021-7946-44b4-acc2-cdb9c29aadc2.jpeg"
