apiVersion: v1
kind: Secret
metadata:
  name: rotardv-painel-secrets
  namespace: rotardv-prod
type: Opaque
stringData:
  NEXTAUTH_SECRET: "sua_chave_secreta_nextauth_com_32_caracteres_min"
  GOOGLE_CLIENT_ID: "seu_google_client_id.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "seu_google_client_secret"
